export interface MortgageStrategyDto {
  id?: string
  order: number
  name?: string
  intro?: string
  minLvr: number
  maxLvr: number
  benefits?: string
  disadvantages?: string
  strategyShort?: string
  strategyLong?: string
  exampleA?: string
  exampleB?: string
  exampleC?: string
  image?: string
  lendersANZ: boolean
  lendersASB: boolean
  lendersBNZ: boolean
  lendersHeartland: boolean
  lendersKiwibank: boolean
  lendersCooperativeBank: boolean
  lendersTSB: boolean
  lendersWestpac: boolean
  criteriaTypeFirstHome: boolean
  criteriaTypeRefinance: boolean
  criteriaTypeNewHome: boolean
  criteriaAge40Plus: boolean
  criteriaLvrLess80: boolean
  criteriaLvr80to85: boolean
  criteriaLvr85to90: boolean
  criteriaLvr90to95: boolean
  criteriaLiveInForNotSure: boolean
  criteriaLiveInForLessThan2Years: boolean
  criteriaLiveInForBetween2And5Years: boolean
  criteriaLiveInForOver5Years: boolean
  ratesStructureVariable?: number
  ratesStructureSixMonths?: number
  ratesStructureOneYear?: number
  ratesStructureEighteenMonths?: number
  ratesStructureTwoYears?: number
  ratesStructureThreeYears?: number
  ratesStructureFourYears?: number
  ratesStructureFiveYears?: number
  selected: boolean
}
